### ISSUE TITLE
TryParse or specific exception throwing

### ISSUE THREAD

**Issue by SeanSobey** [Sage/jsurl#10]
Hi

We are using this as part of our project but only know at runtime whether urls are encoded using jsurl.

Given there is no TryParse or something, I am doing Parse in a try/catch and just sinking all exceptions and assuming the exception means that the url is not encoded in jsurl.

Would it be possibly to implement a TryParse, or just change the "bad JSURL syntax: expected "... and "bad value keyword: "... throw new Error()'s to derived classes? That way we can catch on specific instances and handle the situations that way?

Thanks for any feedback

**Comment by bjouhier** [comment]
Hi @SeanSobey 

I implemented it (sorry for the long delay) and published as 0.1.5.

**Comment by SeanSobeySage** [comment]
Thanks!
