### ISSUE TITLE
Slack double-encoding apostrophes

### ISSUE THREAD

**Issue by nicolaskruchten** [Sage/jsurl#11]
Thanks for this great library! 

I'm using it to carry JSON-like payloads in hash-URLs, and when sending our links via Slack, the popular chat client, it seems to encode the `'` character and then re-encode the resulting output, which means that `'` turns into `%2527`. Presumably another pass would turn it into `%252727` etc. This means that your special-case fix for #6 doesn't work in this case.

The solution I'm looking at is to `decodeURI` repeatedly (likely up to some limit!) until the output matches the input. You may want to consider such a general approach to deal with unnecessary encodings such as these...

**Comment by bjouhier** [comment]
See #4. Maybe I should extend the fix to also handle `%2527`, `%252527`, etc.

This single quote thing is unfortunate. Browsers did not encode it when I designed this but they started doing it to solve a security issue 😞.

**Comment by nicolaskruchten** [comment]
Yeah, it's an unfortunate development... I'm not sure what the relationship is with #4 though...?

My fix for iteratively `decodeURI`ing works fine but something like a regex for `(%(25)?27)->'` might do the trick more surgically. Let me know if you want a PR for that :)

**Comment by bjouhier** [comment]
Yes, I'll welcome a PR. Changing the regex at https://github.com/Sage/jsurl/blob/master/lib/jsurl.js#L86 + a unit test should do the trick.

**Comment by bjouhier** [comment]
The `?` should be `*` in the regex, to handle arbitrary levels of encoding.

**Comment by nicolaskruchten** [comment]
Indeed, I mistyped when I wrote `?` :)

PR sent, thanks for being receptive!

I would still consider the application of `decodeURI` for this library, as even though `jsurl` only uses characters which don't *need* to be encoded, it's still legal to do so as far as I know, and repeated application of `decodeURI` should either fail or converge, as I understand it.

**Comment by bjouhier** [comment]
I published it to NPM as 0.1.5. Thanks for the PR.

**Comment by wmertens** [comment]
@nicolaskruchten you cannot just keep decoding until you encounter a problem. What if I really wanted to send the string `%27`? If you keep decoding, you get `'`, but if you decode as many times as it was encoded, you get `%27`.

**Comment by nicolaskruchten** [comment]
If you wanted to send `%27`, wouldn't `jsurl` encode that as `*2527`?

**Comment by wmertens** [comment]
oh duh, right, nevermind :blush:
