### ISSUE TITLE
Parse error in IE7

### ISSUE THREAD

**Issue by LinoLinux** [Sage/jsurl#2]
As pointed out here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Character_access , accessing single characters through numerical index is a part of ECMAScript5 and is not supported on IE7 and lower. 

All references to s[i] and s[i+1] in parse function should be edited to use charAt() function.

**Comment by bjouhier** [comment]
@LinoLinux Fix probably comes way too late. Sorry for that. I had missed the issue :disappointed:.
